---
title: "Sales Report"
author: "Roy Ruiz"
date: "February 11, 2021"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    code_folding: none
    df_print: paged
    highlight: tango
    number_sections: yes
    theme: flatly
    toc: yes
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    eval = TRUE,
    message = FALSE,
    warning = FALSE,
    dpi = 300,
    fig.align = "center"
    )

# See Options: knitr::opts_chunk$get()

# Load Libraries
# Core
library(tidyverse)
library(lubridate)

# Interactive Visualizations
library(plotly)
library(ggthemes)

# Script to handle data and plot total sales and sales by category
# Script also include currency formatting
source("00_scripts/plot_sales.R")
```

```{r echo=FALSE, results='hide'}
# Bike data
bikes_tbl      <- readRDS("00_bike_data/bikes_tbl.rds")
bikeshops_tbl  <- readRDS("00_bike_data/bikeshops_tbl.rds")
orderlines_tbl <- readRDS("00_bike_data/orderlines_tbl.rds")

bike_orderlines_tbl <- orderlines_tbl %>%
  mutate(order_date = lubridate::ymd(order_date))%>%
  left_join(bikes_tbl,     by = c("product_id" = "bike_id")) %>%
  left_join(bikeshops_tbl, by = c("customer_id" = "bikeshop_id")) %>%
  
  # Add the total price
  mutate(total_price = price_euro * quantity)

bike_orderlines_tbl

# Margins for Time Plots
#margin_sz <- list(l = 20, r = 20, b = 160, t = 20)
```

# Total Sales Charts {.tabset .tabset-fade .tabset-pills}

## Quarterly Sales Trends

```{r echo=FALSE, out.height="600px"}
# Quarterly total sales graph
plot_total_sales(bike_orderlines_tbl, unit = "quarterly", date_format = "%Y", interactive = FALSE)
```

## Monthly Sales Trends

```{r echo=FALSE, out.height="600px"}
# Monthly total sales graph
plot_total_sales(bike_orderlines_tbl, unit = "monthly", date_format = "%B %Y", interactive = FALSE)
```

## Weekly Sales Trends

```{r echo=FALSE, out.height="600px"}
# Weekly total sales graph
plot_total_sales(bike_orderlines_tbl, unit = "weekly", date_format = "%B %d, %Y", interactive = FALSE)
```


# Category Sales Charts {.tabset .tabset-fade .tabset-pills}

## Road {.tabset .tabset-fade .tabset-pills}

### Quarterly

```{r echo=FALSE, out.height="100%"}
# Quarterly sales graph for Road category
plot_categories(bike_orderlines_tbl, category_1 = "Road", category_2 = "All", 
                unit = "quarterly", date_format = "%Y",
                ncol = 1, scales = "free_y",
                interactive = FALSE)
```

### Monthly

```{r echo=FALSE, out.height="100%"}
# Monthly sales graph for Road category
plot_categories(bike_orderlines_tbl, category_1 = "Road", category_2 = "All", 
                unit = "monthly", date_format = "%Y",
                ncol = 1, scales = "free_y",
                interactive = FALSE)
```

### Weekly

```{r echo=FALSE, out.height="100%"}
# Weekly sales graph for Road category
plot_categories(bike_orderlines_tbl, category_1 = "Road", category_2 = "All", 
                unit = "weekly", date_format = "%Y",
                ncol = 1, scales = "free_y",
                interactive = FALSE)
```

## Mountain {.tabset .tabset-fade .tabset-pills}

### Quarterly

```{r echo=FALSE, out.height="100%"}
# Quarterly sales graph for Road category
plot_categories(bike_orderlines_tbl, category_1 = "Mountain", category_2 = "All", 
                unit = "quarterly", date_format = "%Y",
                ncol = 1, scales = "free_y",
                interactive = FALSE)
```

### Monthly

```{r echo=FALSE, out.height="100%"}
# Monthly sales graph for Road category
plot_categories(bike_orderlines_tbl, category_1 = "Mountain", category_2 = "All", 
                unit = "monthly", date_format = "%Y",
                ncol = 1, scales = "free_y",
                interactive = FALSE)
```

### Weekly

```{r echo=FALSE, out.height="100%"}
# Weekly sales graph for Road category
plot_categories(bike_orderlines_tbl, category_1 = "Mountain", category_2 = "All", 
                unit = "weekly", date_format = "%Y",
                ncol = 1, scales = "free_y",
                interactive = FALSE)
```
